# Generated by Django 5.1.4 on 2025-01-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
