# Generated by Django 5.1.4 on 2025-01-05 17:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Клиенты", "verbose_name_plural": "Клиенты"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="token",
            field=models.CharField(
                default=uuid.uuid4,
                max_length=255,
                unique=True,
                verbose_name="User token",
            ),
        ),
    ]
